name: ruqqus_dart
description: A powerful Ruqqus API wrapper written entirely in Dart.
version: 2.0.2

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  ansicolor: ^1.0.5
  dio: ^3.0.10
  event_dart: ^1.0.0
  intl: ^0.16.1